const examplePrompts = [
  `A serene sunset landscape with mountains and a lake in a watercolor art style.`,
  `A futuristic cityscape at night with neon lights in a cyberpunk digital art style.`,
  `A mythical creature blending a lion and a dragon in an abstract painting style.`,
  `A whimsical underwater world with colorful coral reefs and exotic fish in a vibrant and detailed high-resolution photograph.`,
  `A surreal forest scene with floating trees and glowing mushrooms in a fantasy digital art style.`,
  `A steampunk-inspired airship soaring through the clouds in a detailed and realistic digital painting.`,
  `A sci-fi robot character with a sleek and futuristic design in a digital illustration style.`,
  `An abstract artwork using vibrant colors and geometric shapes in an expressive and modern art style.`,
  `A magical book cover with an enchanted forest and mystical creatures in an illustrative fantasy style.`,
  `A retro-style illustration of a vintage car on an open road in a vintage-inspired digital art style.`,
  `A fantastical space scene with planets, galaxies, and shooting stars in a realistic digital painting style.`,
  `A cyberpunk-inspired cityscape with towering skyscrapers and flying vehicles in a futuristic digital art style.`,
  `An abstract painting of artificial intelligence.`,
  `A photo of a Samoyed dog with its tongue out hugging a white Siamese cat.`,
  `A photo of a teddy bear on a skateboard in Times Square.`,
  `A centered explosion of colorful powder on a black background.`,
  `A hand palm with a tree growing on top of it.`,
  `A 3D render of a rainbow-colored hot air balloon flying above a reflective lake.`,
  `A 3D render of an astronaut walking in a green desert.`,
  `A tranquil beach scene with palm trees and turquoise waters in a tropical painting style.`,
  `A close-up photograph of a vibrant bouquet of flowers with shallow depth of field.`,
  `A digital portrait of a person with surreal elements and unique facial features.`,
  `A detailed pencil drawing of an old architectural landmark.`,
  `An abstract representation of music through colorful shapes and patterns.`,
  `A nature-inspired pattern design with intricate botanical elements.`,
  `A mixed media artwork combining acrylic paint, collage, and ink.`,
  `A minimalist black and white photograph capturing architectural lines and symmetry.`,
  `A portrait painting showcasing the emotions and personality of the subject.`,
  `A wildlife photograph capturing a rare and majestic animal in its natural habitat.`,
  `An experimental typography design with creative arrangements of letters and words.`,
  `A conceptual artwork exploring the theme of time and its passage.`,
  `A vibrant watercolor painting of a bustling market scene.`,
  `A digital illustration of a mythical creature from folklore.`,
  `A macro photograph capturing the intricate details of a flower petal.`,
  `An urban sketch capturing the essence of a bustling city street.`,
  `A landscape painting depicting a peaceful countryside during sunrise.`,
  `An abstract sculpture made from recycled materials.`,
  `A mixed media collage representing the beauty of diversity.`,
  `A photorealistic charcoal drawing of an everyday object.`,
  `A digital painting inspired by the colors and patterns of the Northern Lights.`,
  `An architectural visualization of a futuristic building design.`,
  `A still life photograph showcasing the beauty of simple objects.`,
  `A conceptual artwork exploring the intersection of nature and technology.`,
  `A geometric pattern design inspired by traditional tribal art.`,
  `A portrait photograph capturing the essence and character of an elderly person.`,
  `A whimsical children's book illustration with playful characters.`,
  `A mixed media artwork combining photography, painting, and typography.`,
  `An abstract expressionist painting filled with bold brushstrokes and vibrant colors.`,
  `A wildlife documentary photograph capturing a rare behavior of an animal species.`,
  `A digital concept art of a futuristic vehicle or transportation system.`,
  `A landscape photograph showcasing the breathtaking beauty of a mountain range.`,
  `An intricate paper-cutting artwork with delicate and intricate details.`,
  `A conceptual artwork exploring the theme of identity and self-discovery.`,
  `A surreal digital collage combining unexpected elements in a dreamlike composition.`,
  `A botanical illustration showcasing the intricate details of a plant or flower.`,
];

export default examplePrompts;